Add shortcut to toggle overlay
checkly/headless-recorder pull request #151
Opened 2021-08-19 18:01 UTC by ianaya89

# Add shortcut to toggle overlay

## Description
Add shortcut to toggle overlay and re-add screenshot shortcuts:
- `ctrl + k`: Toggle overlay
- `ctrl + shitf + F`: Take full page screenshot
- `ctrl + shitf + E`: Take element screenshot

## Type of change

- [x] New feature (non-breaking change which adds functionality)

## Checklist:

- [x] My code follows the style guidelines of this project. `npm run lint` passes with no errors.
- [x] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes. `npm run test` passes with no errors.

2021-08-19 18:25 UTC, tnolet commented
@ianaya89 can you add a screenshot?

2021-08-19 18:29 UTC, ianaya89 commented
@tnolet done!

2021-08-19 18:30 UTC, tnolet requested changes
😅 almost!

2021-08-19 18:30 UTC, tnolet commented on README.md
> +- `ctrl + shitf + F`: Take full page screenshot
nice typo...`shit`

2021-08-20 07:37 UTC, maxigimenez approved these changes
LGTM 👍 !

2021-08-20 14:59 UTC, merged